### ISSUE TITLE
Unable to disable creating shortcuts

### ISSUE THREAD

**Issue by snowtrr** [SnipeStudio/SnipeStudio_Budjet_manager#43]
**BRIEF:**
Unable to disable creating shortcuts (In installer)

**BUILD_NUMBER:**
0.5.3.1 win

**STEPS_TO_REPRODUCE:**
1. Start install BM
2. Go to page of "Select Shortcuts"

**ACTUAL_RESULTS:**
You have no possibility to disable creating shortcuts

**EXPECTED_RESULTS:**
You have possibility to disable creating shortcuts

**DESK_DESCRIPTION:**
Windows 8.1 Update 3

**ADDITIONAL_INFO:**
![capture](https://cloud.githubusercontent.com/assets/7932759/12778226/acc995a2-ca72-11e5-98c0-4d402c473923.PNG)

**Comment by SteamDragon** [comment]
[Mantis Bug](http://bugs.snipestudio.hol.es/view.php?id=36)
**Priority:** Trivial

**Comment by SteamDragon** [comment]
Will be fixed in release installation package.

**Comment by snowtrr** [comment]
Fixed.
