### ISSUE TITLE
0.5.3 Fails to start without any messages

### ISSUE THREAD

**Issue by SteamDragon** [SnipeStudio/SnipeStudio_Budjet_manager#44]
BRIEF:
0.5.3 Fails to start without any messages

BUILD_NUMBER:
0.5.3.1 win

STEPS_TO_REPRODUCE:
Start to installed with installer SSBM

ACTUAL_RESULTS:
Nothing happens

EXPECTED_RESULTS:
Application runs

DESK_DESCRIPTION:
Windows 8.1 Update 3

**Comment by SteamDragon** [comment]
[Mantis Bug](http://bugs.snipestudio.hol.es/view.php?id=37)
**Severity:** Blocker
**Priority:** immediate

**Comment by SteamDragon** [comment]
Need to recompile installation file. There was insufficient libraries

**Comment by snowtrr** [comment]
Fixed.
