### ISSUE TITLE
Dump data to file 

### ISSUE THREAD

**Issue by wispwisp** [SnipeStudio/SnipeStudio_Budjet_manager#57]
**BRIEF:** Dump data to a file

**BUILD_NUMBER:**

**STEPS_TO_REPRODUCE:**

**ACTUAL_RESULTS:**

**EXPECTED_RESULTS:** dump to txt, xml, pdf, etc... (Also restore form it would be nice)

**DESK_DESCRIPTION:**

**Comment by SteamDragon** [comment]
Done in 0.7
